version: "3.8"
services:
  mynginx:
    build: nginx/
    ports:
      - 80:80
    depends_on:
      - mydjango
    volumes:
      - ~/Documents/nginx:/var/log/nginx
  mydjango:
    build: django
    ports:
      - 8000:8000